name: Split and Commit File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # (ทุกชั่วโมง) (ตามเวลา UTC)
  workflow_dispatch:  # เพิ่มส่วนนี้เพื่อให้ปุ่ม "Run workflow" ปรากฏขึ้น

permissions:
  contents: write

jobs:
  split_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          curl -o outbound.txt https://raw.githubusercontent.com/bitwire-it/ipblocklist/refs/heads/main/outbound.txt
      - name: Split and commit
        run: |
          mkdir -p output
          split -l 100000 --numeric-suffixes outbound.txt output/ipOutboundBlocklist_part_

      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Add new parts from outbound.txt" || echo "No changes to commit"
          git push
